tasks:
  # Hasura Engine
  # ======================
  - name: Hasura Engine
    init: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
    command: make start
    openIn: right

  # Hasura Events
  # ======================
  - name: Hasura Events
    command:
      bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4010/healthz)" != "200" ]]; do sleep 5; done'
      && docker-compose up hasura-events-test
      && docker-compose logs -f hasura-events
    openIn: right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 4010
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8008
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
    - EditorConfig.EditorConfig@0.14.4:EjFaoTaOf8wRmwR0LNY51A==
